Use production Deepgram for WS transcription
deepgram-devs/jamfest pull request #8
Opened 2022-10-19 16:36 UTC by mlodato517

## This Commit

Updates the repo to use the official production Deepgram endpoint for WS transcription instead of the proxy.

## Why?

Because that is more correct and stable. Then we can take down the proxy and stop managing it.

## Notes

This requires those building the repo to compile a token into the binary which will be available on the client. We think this is fine for now and can come up with something else if we want later.

2022-10-19 16:37 UTC, mlodato517 commented on src/main.rs
> -            &asset_server,
This was just a `clippy` lint since I have a newer Rust locally and this repo doesn't have a `rust_toolchain` file :shrug:

2022-10-19 16:37 UTC, mlodato517 commented on src/microphone.rs
> +    let credentials = std::env!("DEEPGRAM_API_KEY");
Huge thanks to Huston for this stuff!

2022-10-19 16:37 UTC, mlodato517 commented on src/microphone.rs
> +        closure.forget();
Oh yeah, whoops, should comment this and the `Box::leak` now that it looks like this works

2022-10-19 17:19 UTC, nikolawhallon commented on src/microphone.rs
>  }
the name of this function is not (no longer?) good - it simply passes audio on to the websocket

2022-10-19 17:20 UTC, nikolawhallon commented on src/microphone.rs
> +fn register_listener_callback(
put a new line here?

2022-10-19 17:21 UTC, nikolawhallon commented on src/microphone.rs
> +fn register_listener_callback(
I don't understand the name of this function, maybe this should be handle asr? or setup asr handler?

2022-10-19 17:22 UTC, nikolawhallon commented on src/microphone.rs
> +    let credentials = std::env!("DEEPGRAM_API_KEY");
this doesn't "setup deepgram" - it "connects to deepgram" - I feel like defining things like "on message" are part of "setting up deepgram"

2022-10-19 17:22 UTC, nikolawhallon requested changes
my comments aren't amazing, I think just renaming some functions might make things crystal clear

also, more comments around the weird things

2022-10-19 20:05 UTC, mlodato517 commented on README.md
> +You'll need a [Console token][console] to authenticate to Deepgram. You'll
795adb6902596b019f6bb3ebdfc73fa9c044e840

2022-10-19 20:05 UTC, mlodato517 commented on src/microphone.rs
>  }
9dffacadd5de28c5c3dee1e9721917be8358ba60

2022-10-19 20:05 UTC, mlodato517 commented on src/microphone.rs
> +fn register_listener_callback(
9919e858eca5023f212ab90e66c6c7ad4a5fe4a3

2022-10-19 20:05 UTC, mlodato517 commented on src/microphone.rs
> +fn register_listener_callback(
7a01de60de3e3d0b901f0d9e055fa2f23581cda8

2022-10-19 20:05 UTC, mlodato517 commented on src/microphone.rs
> +    let credentials = std::env!("DEEPGRAM_API_KEY");
e859ec4a02dfa54416c4262059e6450a59da58a5

2022-10-19 20:08 UTC, nikolawhallon approved these changes
11/10

2022-10-19 20:19 UTC, nikolawhallon commented
Merge it! Merge it! Merge it! Merge it!

2022-10-20 12:34 UTC, mlodato517 commented on src/microphone.rs
> +fn send_audio_to_deepgram(
You know what, yeah, might as well for consistency haha. I'll also update `proxy_speech_events` to `proxy_speech_events_to_bevy`. Which is a little weird because `bevy` isn't a hosted service :thinking: `proxy_speech_events_to_game`? Well I mean the microphone plugin is already part of the game :dizzy_face: Okay fuck it I won't change that one haha

Updated in 3532916!

2022-10-20 12:34 UTC, mlodato517 commented
I'll squash and merge and apologies if you didn't want that newer change - I'll update it in a follow up if you want me to!

2022-10-20 12:37 UTC, merged